import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { db } from '../lib/db'

async function getServerSideProps(context: any) {
  // const res = await fetch(`https://bb.kongroo.xyz/${bingo}`);
  // const data = await res.json;
  const games = await db
      .collection("games")
      .find({})
      .toArray();

  const game = games[0];

  return {
      props: {game},
  }
}

//@ts-ignore
const Home: NextPage = ( { game } ) => {
  console.log(game);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossOrigin="anonymous"/>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bingo!
        </h1>

        { game.data.map((cell) => {
          <div className="col-12 col-lg-4 col-md-6">
            <button type="button" className="btn btn-primary" onClick={getServerSideProps}>{cell}</button>
          </div>
        }) }
      </main>

      <footer className={styles.footer}>
        <p>kongi</p>
      </footer>
    </div>
  )
}

export default Home
